#define EXIT_VIEW 0
#define LOGIN_VIEW 1
#define LOGOUT_VIEW 2
#define MAIN_VIEW 3
#define PROFILE_VIEW 4
#define REGISTER_VIEW 5
#define REQUESTFORWORKER_VIEW 6
#define SPLASH_VIEW 7
#define UPDATENAME_VIEW 8
#define UPDATEPASSWORD_VIEW 9
#define WELCOME_VIEW 10
#define WORKER_VIEW 11

#define ADMIN_ROLE 1
#define CLIENT_ROLE 2
#define WORKER_ROLE 3

#define REDIRECT_TIME 3