#define ADMINTOOLS_VIEW 0
#define ADMIN_VIEW 1
#define BESTWORSTCLIENTSSTATISTICS_VIEW 2
#define BESTWORSTWORKERSSTATISTICS_VIEW 3
#define CLIENTDIVISION_VIEW 4
#define CLIENTSSTATISTICS_VIEW 5
#define CLIENT_VIEW 6
#define CREATEREQUEST_VIEW 7
#define CURRENTREQUESTS_VIEW 8
#define DELETEREQUEST_VIEW 9
#define EXIT_VIEW 10
#define FIREWORKER_VIEW 11
#define LOGIN_VIEW 12
#define LOGOUT_VIEW 13
#define MAIN_VIEW 14
#define PROFILE_VIEW 15
#define REGISTER_VIEW 16
#define REQUESTDATA_VIEW 17
#define REQUESTFORWORKER_VIEW 18
#define REQUESTMENU_VIEW 19
#define SPLASH_VIEW 20
#define UPDATENAME_VIEW 21
#define UPDATEPASSWORD_VIEW 22
#define WELCOME_VIEW 23
#define WORKERDIVISION_VIEW 24
#define WORKERSSTATISTICS_VIEW 25
#define WORKER_VIEW 26

#define ADMIN_ROLE 1
#define CLIENT_ROLE 2
#define WORKER_ROLE 3

#define PENDING 1
#define PROCESSING 2
#define CONCLUDED 3

#define REDIRECT_TIME 3